env:
 

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
      - <<: *osx
        osx_image: xcode9.4
      - <<: *osx
        osx_image: xcode10

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
