build: false

environment:

    matrix:
        - PYTHON_HOME: "C:\\Python27"
        - PYTHON_HOME: "C:\\Python35"
        - PYTHON_HOME: "C:\\Python36"
        - PYTHON_HOME: "C:\\Python37"
        - PYTHON_HOME: "C:\\Python27-x64"
        - PYTHON_HOME: "C:\\Python35-x64"
        - PYTHON_HOME: "C:\\Python36-x64"
        - PYTHON_HOME: "C:\\Python37-x64"

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install python-libsbml-experimental --upgrade

test_script:
  - python test_render.py
